services:
  # Backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - mynetwork

  # Frontend
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    networks:
      - mynetwork
    depends_on:
      - api

  # Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    restart: always
    ports:
      - 5175:80
    networks:
      - mynetwork
    depends_on:
      - api
      - web

networks:
  mynetwork:
    driver: bridge
